'''3. Enigma   (with reflection) key  =[5, 11] #initial 
Rotors:
 L_1=[20, 3, 24, 18, 8, 5, 15, 4, 7, 11, 0, 13, 9, 22, 12, 23, 10, 1, 19, 21, 17, 16, 2, 25, 6, 14]
 L_2=[8, 13, 24, 18, 9, 0, 7, 14, 10, 11, 19, 25, 4, 17, 12, 21, 15, 3, 22, 2, 20, 16, 23, 1, 6, 5]
Reflector s=[2, 4, 0, 6, 1, 11, 3, 8, 7, 13, 16, 5, 15, 9, 18, 12, 10, 19, 14, 17, 25, 22, 21, 24, 23, 20]
Decrypt the cipher 
URDZH WVCZI RVTSW HIIUF URIFQ 
IYUFY WIEOT KGHTA EPIIO YWUMD 
MXOBC HDUUL ZKGFH PWVSH AFWNM 
AAHYH EWTZR BPVJH HQCOQ VJKVV 
GIFQM JTCBX LYUTM AGKBP BTQYV 
BPUOR FDLRA SMTVC WIRRD SXYCX 
OOGDZ MDOFF XITTZ GTRXG AJLIY 
HSCCV CVGYW NHJAL ZVXME TOAKW 
HWCRL DWSDR EAVDI DJFIE XWXIH 
FFESH YRVTK TBLUC GCLIB NHVMN 
TTXTG QINAX SACOO YUUSU IKBHP 
WCKRH KNPIC PXSWJ VJCJW MFJPT 
NVGHI HPFGA EFUTM GTSUC ULFGO 
PFHED XEKIL CCRAV FXVXJ NBQPA 
KGZOJ BIFXJ CKYGK WFDFV OAPPI 
HHQWQ OCXCM VOOLE NWNZQ HTMNK 
FJTMU AGOVW AJSUF PKSJV XOIVB 
BJJHM FKDSK TXOQY DQSQQ JQUOV 
ICHMB NXBOQ CGWDJ FNHGE DAUSY 
NIUCB HTRGL YSPGV GUUMZ PNFLA 
YZFUV BCXCG UZUEC RJENR KWANP 
IWOOB VEYME MPUJJ VGWPH WXZWO 
HQZDN PIVCD DPILC JKZIZ AVTMU 
XFYVV MKEFK SLQSL GQFQQ TUCXK 
AYNDW RYVTA MJPKC JTZET WSVZD 
RLFGF LFAFJ VFHHQ WX'''

cp='''URDZH WVCZI RVTSW HIIUF URIFQ 
IYUFY WIEOT KGHTA EPIIO YWUMD 
MXOBC HDUUL ZKGFH PWVSH AFWNM 
AAHYH EWTZR BPVJH HQCOQ VJKVV 
GIFQM JTCBX LYUTM AGKBP BTQYV 
BPUOR FDLRA SMTVC WIRRD SXYCX 
OOGDZ MDOFF XITTZ GTRXG AJLIY 
HSCCV CVGYW NHJAL ZVXME TOAKW 
HWCRL DWSDR EAVDI DJFIE XWXIH 
FFESH YRVTK TBLUC GCLIB NHVMN 
TTXTG QINAX SACOO YUUSU IKBHP 
WCKRH KNPIC PXSWJ VJCJW MFJPT 
NVGHI HPFGA EFUTM GTSUC ULFGO 
PFHED XEKIL CCRAV FXVXJ NBQPA 
KGZOJ BIFXJ CKYGK WFDFV OAPPI 
HHQWQ OCXCM VOOLE NWNZQ HTMNK 
FJTMU AGOVW AJSUF PKSJV XOIVB 
BJJHM FKDSK TXOQY DQSQQ JQUOV 
ICHMB NXBOQ CGWDJ FNHGE DAUSY 
NIUCB HTRGL YSPGV GUUMZ PNFLA 
YZFUV BCXCG UZUEC RJENR KWANP 
IWOOB VEYME MPUJJ VGWPH WXZWO 
HQZDN PIVCD DPILC JKZIZ AVTMU 
XFYVV MKEFK SLQSL GQFQQ TUCXK 
AYNDW RYVTA MJPKC JTZET WSVZD 
RLFGF LFAFJ VFHHQ WX'''

abc='ABCDEFGHIJKLMNOPQRSTUVWXYZ'
n=len(abc)
[k1,k2]  =[5, 11]
L_1=[20, 3, 24, 18, 8, 5, 15, 4, 7, 11, 0, 13, 9, 22, 12, 23, 10, 1, 19, 21, 17, 16, 2, 25, 6, 14]
L_2=[8, 13, 24, 18, 9, 0, 7, 14, 10, 11, 19, 25, 4, 17, 12, 21, 15, 3, 22, 2, 20, 16, 23, 1, 6, 5]

L_1a=[L_1.index(i) for i in range(0,n)]
L_2a=[L_2.index(i) for i in range(0,n)]

def prep(t):
    tn=''
    for r in t:
        if r in abc: tn+=r
    return [abc.index(r) for r in tn]

cpn=prep(cp)
def rotor(a,m,lb):
    c=(a+m)%n
    c=lb[c]
    return (c-m)%n

def encr(r,k,k1,k2):
    m1=k%n
    m2=(k-m1)//n
    m1=m1+k1
    m2=m2+k2
    c=rotor(r,m1,L_1)
    return rotor(c,m2,L_2)

def dencr(c,k,k1,k2):
    m1=k%n
    m2=(k-m1)//n
    m1=m1+k1
    m2=m2+k2
    c=rotor(c,m2,L_2a)
    return rotor(c,m1,L_1a)

def encrf(c,k,k1,k2):
    c=encr(c,k,k1,k2)
    c=s[c] #reflection
    return dencr(c,k,k1,k2)

c=encrf(10,23,11,21)

result=''
for i in range(0, len(cpn)):
    result+=abc[encrf(cpn[i], i,k1,k2)]

print(result)



                   